### ISSUE TITLE
Problem decoding YBR_* photometric interpretations

### ISSUE THREAD

**Issue by PalminX** [Efferent-Health/Dicom-native#1]
First of all thanks for your excellent work with Dicom-native, it works great for JPEG-LS under .NET Core!

It seems there is an issue with decoding Photometric Interpretation of YBR_*

### Expected results
* Images should be rendered the same, regardless of Photometric Interpretation:
![grafik](https://user-images.githubusercontent.com/28887826/56135861-e34ece00-5f91-11e9-8254-38c92072fcb9.png)

### Actual results
* Images with Photometric Interpretation of YBR_FULL or YBR_FULL_422 are rendered wrong:
![grafik](https://user-images.githubusercontent.com/28887826/56135876-eb0e7280-5f91-11e9-8e35-bd0a3b1916a8.png)

**Comment by PalminX** [comment]
The YBR_* images are rendered correctly when just using the standard fo-dicom without [Dicom-native](https://github.com/Efferent-Health/Dicom-native)

**Comment by PalminX** [comment]
# Color Test Pattern DICOM images

This archive contains DICOM SecondaryCaptureImageStorage color test pattern images, the original file is available at https://pixabay.com/vectors/test-pattern-tv-tv-test-pattern-152459/.

The test pattern has been converted to DICOM RGB using [MeVisLab](https://www.mevislab.de/).
Subsequently, the RGB image was converted to
* 8 bit and 16 bit PALETTE COLOR images using [dcmquant](https://support.dcmtk.org/docs/dcmquant.html)
* JPEG-LS and JPEG-Baseline images using [dcmcjpeg](https://support.dcmtk.org/docs/https://support.dcmtk.org/docs/dcmcjpeg.html)

| File                                  	|  Transfer Syntax UID  (0002,0010)                	|  Photometric Interpretation   (0028,0004) 	|  RedPaletteColorLookupTableDescriptor   (0028,1101) 	|
|---------------------------------------	|--------------------------------------------------	|-------------------------------------------	|-----------------------------------------------------	|
| TestPattern_RGB.dcm                   	| LittleEndianExplicit                             	| RGB                                       	| N.A.                                                	|
| TestPattern_Palette.dcm               	| LittleEndianExplicit                             	| PALETTE COLOR                             	| 256\0\8                                             	|
| TestPattern_Palette_16.dcm            	| LittleEndianExplicit                             	| PALETTE COLOR                             	| 256\0\16                                            	|
| TestPattern_JPEG-LS_RGB.dcm           	| JPEGLossless:Non-hierarchical-1stOrderPrediction 	| RGB                                       	| N.A.                                                	|
| TestPattern_JPEG-Baseline_YBRFull.dcm 	| JPEGBaseline                                     	| YBR_FULL                                  	| N.A.                                                	|
| TestPattern_JPEG-Baseline_YBR422.dcm  	| JPEGBaseline                                     	| YBR_FULL_422                              	| N.A.                                                	|

These test patterns can be used under a [Creative Commons Attribution 3.0 Unported License.](https://creativecommons.org/licenses/by/3.0/)

Bernd Kuemmerlen (bkuemmer@gmx.net)

Version: 2.0, 2019-04-15


[TestPattern_Samples.zip](https://github.com/Efferent-Health/Dicom-native/files/3080325/TestPattern_Samples.zip)

**Comment by PalminX** [comment]
The issue can be reproduced by trying to render ```TestPattern_JPEG-Baseline_YBRFull.dcm``` and ```TestPattern_JPEG-Baseline_YBR422.dcm```

All other instances render correctly.

**Comment by jaime-olivares** [comment]
Hi @PalminX 
Thanks for your extensive analysis of the library. We will take some time to analyze this and surely will arrive to a solution. I will try to compare what fo-dicom does differently, as our library is based on Dicom.Desktop.

**Comment by PalminX** [comment]
Looking at the image output, it seems that there is no colorspace conversion going on at all, the wrong image looks like YBR data directly interpreted as RGB.

**Comment by PalminX** [comment]
Here is an update to the test pattern image archive I uploaded earlier, this now includes JPEG 2000 as well as RLE-encoded images.
In addition, the color values are now true RGB, i.e. Red is FF0000 etc.

# Color Test Pattern DICOM images

This archive contains DICOM SecondaryCaptureImageStorage color test pattern images (PM5644), the original file is available at [PM5644-1920x1080](https://commons.wikimedia.org/wiki/File:PM5644-1920x1080.gif).

The test pattern has been converted to DICOM RGB using [MeVisLab](https://www.mevislab.de/).
Subsequently, the RGB image was converted to
* 8 bit and 16 bit PALETTE COLOR images using [dcmquant](https://support.dcmtk.org/docs/dcmquant.html)
  * ```dcmquant.exe PM5644-960x540_RGB.dcm PM5644-960x540_Palette_8.dcm```
  * ```dcmquant.exe +pe PM5644-960x540_RGB.dcm PM5644-960x540_Palette_16.dcm```
* JPEG-Lossless and JPEG-Baseline images using [dcmcjpeg](https://support.dcmtk.org/docs/dcmcjpeg.html)
  * ```dcmcjpeg.exe PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-Lossless_RGB.dcm```
  * ```dcmcjpeg.exe +eb PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-Baseline_YBR422.dcm```
  * ```dcmcjpeg.exe +eb +s4 PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-Baseline_YBRFull.dcm```
* JPEG-LS images using [dcmcjpls](https://support.dcmtk.org/docs/dcmcjpls.html)
  * ```dcmcjpls.exe PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-LS_Lossless.dcm```
  * ```dcmcjpls.exe +en PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-LS_NearLossless.dcm```
* JPEG 2000 and RLE encoded images using [gdcmconv](http://gdcm.sourceforge.net/html/gdcmconv.html)
  * ```gdcmconv.exe -K  PM5644-960x540_RGB.dcm PM5644-960x540_JPEG2000-Lossless.dcm```
  * ```gdcmconv.exe -K -Y  PM5644-960x540_RGB.dcm PM5644-960x540_JPEG2000-Lossy.dcm```
  * ```gdcmconv.exe -K -Y -r 50 PM5644-960x540_RGB.dcm PM5644-960x540_JPEG2000-Lossy50.dcm```
  * ```gdcmconv.exe -K -Y -r 50 PM5644-960x540_RGB.dcm PM5644-960x540_RLE-Lossless.dcm```

| File                                     	|  Instance Number (0020,0013) 	|  Transfer Syntax UID  (0002,0010)                	|  Photometric Interpretation   (0028,0004) 	|  RedPaletteColorLookupTableDescriptor   (0028,1101) 	|
|------------------------------------------	|------------------------------	|--------------------------------------------------	|-------------------------------------------	|-----------------------------------------------------	|
| PM5644-960x540_RGB.dcm                   	| 1                            	| LittleEndianExplicit                             	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_Palette_8.dcm             	| 2                            	| LittleEndianExplicit                             	| PALETTE COLOR                             	| 256\0\8                                             	|
| PM5644-960x540_Palette_16.dcm            	| 3                            	| LittleEndianExplicit                             	| PALETTE COLOR                             	| 256\0\16                                            	|
| PM5644-960x540_JPEG-Lossless_RGB.dcm     	| 4                            	| JPEGLossless:Non-hierarchical-1stOrderPrediction 	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG-Baseline_YBR422.dcm  	| 5                            	| JPEGBaseline                                     	| YBR_FULL                                  	| N.A.                                                	|
| PM5644-960x540_JPEG-Baseline_YBRFull.dcm 	| 6                            	| JPEGBaseline                                     	| YBR_FULL_422                              	| N.A.                                                	|
| PM5644-960x540_JPEG-LS_Lossless.dcm      	| 7                            	| JPEGLSLossless                                   	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG-LS_NearLossless.dcm  	| 8                            	| JPEGLSLossy                                      	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG2000-Lossless.dcm     	| 9                            	| JPEG2000LosslessOnly                             	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG2000-Lossy.dcm        	| 10                           	| JPEG2000                                         	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG2000-Lossy50.dcm      	| 11                           	| JPEG2000 (50% Compression Ratio)                 	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_RLE-Lossless.dcm          	| 12                           	| RLELossless                                      	| RGB                                       	| N.A.                                                	|

These DICOM images can be used under a [Creative Commons Attribution 3.0 Unported License.](https://creativecommons.org/licenses/by/3.0/)

Bernd Kuemmerlen (bkuemmer@gmx.net)

Version: 3.0, 2019-04-18

[TestPattern_Samples_V3.zip](https://github.com/Efferent-Health/Dicom-native/files/3094926/TestPattern_Samples_V3.zip)

**Comment by PalminX** [comment]
* Instances 5 and 6 are rendered incorrectly, all other instances are fine!
* In the standard fo-dicom, Instances 9, 10, and 11 are rendered incorrectly, see https://github.com/fo-dicom/fo-dicom/issues/850

**Comment by jaime-olivares** [comment]
Hi PalminX,
Thanks for this valuable contribution. We will evaluate the sample images next week, because of the Easter holidays.

**Comment by PalminX** [comment]
@jaime-olivares, any update on this issue?

**Comment by PalminX** [comment]
@jaime-olivares, did you have any chance to look into this yet?

Thanks for any help.

**Comment by jaime-olivares** [comment]
Hi again, 
We have uploaded a new test version (see https://www.nuget.org/packages/Efferent.Native/3.8.2-test1).
That should reduce the number of wrong cases. Please review again and let us know if there are some remaining.

**Comment by PalminX** [comment]
I have tested with Efferent.Native 3.8.2-test1, and unfortunately, it seems that there are still issues.

Looking at the test data I provided above, I get the following results:
* Instances 2 and 3 (Palette Color): colors are rendered incorrectly:
![grafik](https://user-images.githubusercontent.com/28887826/57678113-cd800780-7628-11e9-9723-2e1f92403956.png)

* Instances 5 and 6 (YBR_*): colors are rendered incorrectly:
![grafik](https://user-images.githubusercontent.com/28887826/57678129-d83a9c80-7628-11e9-8235-3198878fecce.png)

The other instances are rendered fine.

**Comment by jaime-olivares** [comment]
Hi @PalminX 
Thanks for coming back. I can see the palette is still not handled explicitly on code. Not sure about cases 5 and 6.
Can you tell what cases were solved in the last version?
Thanks.

**Comment by PalminX** [comment]
To me it looks as if nothing has changed between 3.8.1 and 3.8.2-test1, unfortunately... Maybe I am doing something wrong?

Are you able to render instance 5 and 6 correctly?

**Comment by PalminX** [comment]
Please disregard the wrong rendering of instances 2 and 3 (PALETTE COLOR images). I tested agains fo-dicom 4.0.1, which still has [#817](https://github.com/fo-dicom/fo-dicom/issues/817).

Using the current development branch of fo-dicom, the only remaining issue is the wrong rendering of instances 5 and 6 (YBR_* images)

**Comment by jaime-olivares** [comment]
Hi @PalminX,
Tomorrow we will add some tests in the source code so we can be on the same page.

**Comment by PalminX** [comment]
Thanks, I really appreciate your hard work on this.

**Comment by jaime-olivares** [comment]
We fully automated the build process with Azure Pipelines. Now we can speak in the same language.

Our trial images are generated from /test1 and released [here](https://github.com/Efferent-Health/Dicom-native/releases) so you can inspect them.

I haven't analyzed them in depth yet, but will.

**Comment by jaime-olivares** [comment]
UPDATE: Found a bug in fo-dicom. The photometric interpretation was not being updated to RGB. See commit [98f40e8](https://github.com/Efferent-Health/Dicom-native/commit/98f40e898000da80cf2d00c72a3a5f3f3c169a8c) and [last release notes](https://github.com/Efferent-Health/Dicom-native/releases/tag/v3.8.2-test3)

Use nuget version 3.8.2-test3 for testing

**Comment by PalminX** [comment]
Hello Jaime,

today I tried https://www.nuget.org/packages/Efferent.Native/3.8.2-test4 in our project, and I still have the same issue that the YPR_* images are not rendered correctly. I see that the output of your tests look OK, even though I didn't really have a look to see what exactly the tests are doing.

We are just using ```var bitmap = image.RenderImage(frame).As<Bitmap>();``` where image is a DicomImage, and we have injected the Efferent.Native codec as documented:
```            Dicom.Imaging.Codec.TranscoderManager.SetImplementation(new Efferent.Native.Codec.NativeTranscoderManager());```

Do you have any idea why this is not working for us?

**Comment by PalminX** [comment]
I completely cleaned my nuget cache to make sure that I am using the correct version, and I can confirm that disabling the Efferent.Native.Codec again will result in correct rendering of the two YBR_* instances (instance 5 and 6) with the default fo-dicom

**Comment by jaime-olivares** [comment]
Hi @PalminX 
It will be better if you post here your full test project.

**Comment by PalminX** [comment]
I have now added a RenderImages test which shows the issue. So you can disregard my previous comment https://github.com/Efferent-Health/Dicom-native/issues/1#issuecomment-496909501

**Comment by PalminX** [comment]
Doing some more analysis of the issue, I think at least one part of the issue is located here:

https://github.com/fo-dicom/fo-dicom/blob/146d9cb2b7b200c9ec8ce8c178873fec0c71c95d/DICOM/Imaging/DicomImage.cs#L355

In the case of the two example instances which render incorrectly, the DicomImage.CreateDicomPixelData() method sets `pixelData.PhotometricInterpretation = PhotometricInterpretation.Rgb`, which (I think) makes the Efferent.Native transcode think that there's nothing to be decoded when rendering.

In my example code DicomConsoleTest.zip, this means that the DicomImage object which is created at line 57:
```var img = new DicomImage(file);```
has a PhotometricInterpretation of {RGB}, but the actual PixelData of the DicomImage is still in YBR_FULL or YBR_FULL_422.

Since my understanding of the transcoder is still a bit hazy, this is only part of what could explain this. Right now I am struggling to debug into the Decode() method of DicomJpegCodec...

**Comment by PalminX** [comment]
Is somebody still looking into this?

**Comment by PalminX** [comment]
I can confirm that the latest version 3.8.2-test5 fixes this issue

**Comment by PalminX** [comment]
Thanks for your work on getting this finally fixed.

**Comment by jaime-olivares** [comment]
Hi @PalminX 
Thanks for validating this. We will have a final release at nuget today.

**Comment by jaime-olivares** [comment]
Released as 3.8.2: https://www.nuget.org/packages/Efferent.Native/3.8.2

**Comment by alberto-pellizzon** [comment]
Greetings, unfortunately I have this issue as well. I am using the following packages:
_fo-dicom_ v5.0.1, _fo-dicom.Codecs_ v5.0.2, _fo-dicom.Imaging.ImageSharp_ v5.0.1.
If I try to use the latest version of _Efferent.Native_ (v4.1.0), the description tells me _"Cross-platform Dicom native transcoder for fo-dicom. This is a legacy version. Prefer to use fo-dicom.Codecs 5.x instead."_, therefore I switched to _fo-dicom.Codecs_ v5.0.2.
Using the same dataset from the above thread, the two images having _JPEGBaseline_ as Transfer Syntax, are exported with scrambled colors.
Any feedback would be appreciated.
