### ISSUE TITLE
Efferent.Native-linux64.so not found/not working when running in Docker (Debian 9.8)

### ISSUE THREAD

**Issue by PalminX** [Efferent-Health/Dicom-native#2]
We have a .NET Core project which uses Dicom-native and runs fine on Windows (except #1).

When deploying on Docker, during runtime, the app does not find the ```Efferent.Native-linux64.so```

I have checked that shared libraries are available under ```/root/.nuget/packages/efferent.native/3.8.0/runtimes```, but they are not accessible to the library loader. I tried to link one of the ```Efferent.Native-linux64.so``` to ```/usr/lib```, but then I got a runtime error during decoding.

The Docker image is based on mcr.microsoft.com/dotnet/core/sdk:2.2 and basically just runs ```dotnet build``` on our project.
The regular fo-dicom packages work as expected in this environment.

Is there anything we are doing wrong, or is there anything that needs to be adapted to make Dicom-native work in a Docker container (running Debian 9.8)?

**Comment by PalminX** [comment]
Is it that ```Efferent.Native-linux64.so``` needs to be compiled separately under Debian?

**Comment by PalminX** [comment]
I managed to build my own `Efferent.Native-linux64.so` with CMake/make under Debian 9.8 and linked the .so to /usr/lib, and I get the following runtime error when trying to render a JPEG Lossless instance:

```
2019-04-16 09:34:50,110 --[46:27] --ERROR  --The image could not be rendered. An internal server error occurred, possibly caused by an invalid or unsupported DICOM datasetSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Dicom.Imaging.Render.ImageGraphic.RenderImage(ILUT lut) in C:\fo-dicom\DICOM\Imaging\Render\ImageGraphic.cs:line 231
   at Dicom.Imaging.DicomImage.RenderImage(Int32 frame) in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 256
...
```

**Comment by jaime-olivares** [comment]
hi @PalminX 
This seems to be a NuGet issue. We need to pack the .so under a more generic /runtimes/linux folder or specific /runtimes/debian folders
I will generate a nuget package in the following days.

**Comment by PalminX** [comment]
Thanks for looking into this.

**Comment by jaime-olivares** [comment]
Hi again,
I have published https://www.nuget.org/packages/Efferent.Native/3.8.0-test4
It contains a runtime for the generic 'linux-64' RID and should work with many linux distributions.
As explained here: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by PalminX** [comment]
Hello Jaime,
I tested again with https://www.nuget.org/packages/Efferent.Native/3.8.0-test4, and now our application runs fine in Docker under Debian.

Thanks a lot, and I would appreciate if this could be put into the official nuget package as well

**Comment by jaime-olivares** [comment]
Will be ready tomorrow

**Comment by jaime-olivares** [comment]
Done. Please try with the new nuget package once it is available: https://www.nuget.org/packages/Efferent.Native/3.8.1
