### ISSUE TITLE
Question: Possibility to use NativeTranscoderManager only for specific codecs?

### ISSUE THREAD

**Issue by PalminX** [Efferent-Health/Dicom-native#3]
I was wondering if it is somehow possible to use the Efferent.Native TranscoderManager more selectively, e.g. enable it for JPEGLossless and disable it for JPEG2000?

Any help would be appreciated.

**Comment by jaime-olivares** [comment]
I don't think it will be in the roadmap anytime soon. Our goal is to cover 100% of the use cases.
