### ISSUE TITLE
Cross platform c++ shared library

### ISSUE THREAD

**Issue by unosbaghaie** [Efferent-Health/Dicom-native#5]
Hi 
Thanks for your library. it is perfect.

I have a question which it is not related to your library. But because I couldn't find my answer in internet, I ask it here. 

I am writing a cross platform c++ shared library which I want to call it from c#. 
in windows I find the c++ shared object (dll) and everything is ok. but in linux my c# app cannot find the so file. 

Can you tell me where I should place my so file?
[For more info the source is available here](https://stackoverflow.com/questions/57756328/cross-platform-c-integrated-with-c-sharp-in-linux-and-windows)

**Comment by jaime-olivares** [comment]
I see the question is answered already in StackOverflow.
